# Generated by Django 5.0.4 on 2024-04-29 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photolog', '0002_photo_created_at_photo_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='updated_at',
        ),
    ]
