# Generated by Django 5.0.4 on 2024-04-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photolog', '0003_remove_photo_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(),
        ),
    ]
